bata/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls', namespace='menu')),
    path('hitung/', include('hitung.urls', namespace='hitung')),
    path('menu/', include('menu.urls', namespace='menu')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hitung/urls.py
from django.urls import path
from . views import *
app_name = 'hitung'

urlpatterns = [
    path('batamerah', batamerah, name='batamerah'),
    path('bataringan', bataringan, name='bataringan'),
    path('batako', batako, name='batako'),
    path('panduan', panduan, name='panduan'),
    path('harga', harga, name='harga'),
    path('panduan2', panduan2, name='panduan2'),
]

menu/urls.py
from django.urls import path
from . views import *
app_name = 'menu'

urlpatterns = [
    path('', splash, name='splash'),
    path('menu/', menu, name='menu'),
]

hitung/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models

# Create your models here.

hitung/views.py
from django.shortcuts import render

# Create your views here.


def batamerah(request):

    return render(request, 'batamerah.html')


def bataringan(request):

    return render(request, 'bataringan.html')


def batako(request):

    return render(request, 'batako.html')


def panduan(request):

    return render(request, 'panduan.html')
def panduan2(request):

    return render(request, 'panduan2.html')

def harga(request):

    return render(request, 'harga.html')

menu/views.py
from django.shortcuts import render

# Create your views here.


def menu(request):

    return render(request, 'menu.html')

def splash(request):

    return render(request, 'menu2.html')

hitung/templates/batako.html
{%extends 'base2.html'%} {% load static %} {%block content%} <br /><br />
<center>
  <div class="navbar">
  <div class="row">
    <div class="column">
      <a href="{% url 'menu:menu' %}"><img src="{%static 'images/back.png'%}" alt="" id="back"></a>
      <br />
    </div>
    <div class="column">
      <h4>Batako</h4>
      <br />
    </div>
    <div class="column">
     <img src="{%static 'images/icon.png'%}" alt="" id="back">
      <br />
    </div>
  </div>
  </div>
  <br />

  <label for="n1">Tinggi Dinding</label><br />
  <img src="{%static 'images/m.png'%}" alt="" id="icon2" />
  <input type="text" id="n1" /><br /><br />

  <label for="n2">Panjang Dinding</label><br />
  <img src="{%static 'images/m.png'%}" alt="" id="icon2" />
  <input type="text" id="n2" /><br />

  <p id="lebihlengkap" onclick="openForm();">Lebih Detail <b>&#8645;</b></p>

  <div id="cdetail">
    <p id="lebihlengkap" onclick="closeForm();">Lebih Detail <b>&#8645;</b></p>
    <label for="n3">Harga per pcs (default = Rp. 2.500)</label><br />
    <img src="{%static 'images/rp.png'%}" alt="" id="icon3" />
    <input type="text" id="n3" /><br /><br />

    <label for="n3">Bata per m2 (default = 11)</label><br />
    <img src="{%static 'images/buah.png'%}" alt="" id="icon3" />
    <input type="text" id="n4" /><br /><br />
  </div>

  <button onclick="calc();" id="hitung">HITUNG</button><br />
  <br /><br />
  <label>Jumlah buah bata</label><br />
  <img src="{%static 'images/buah.png'%}" alt="" id="icon4" />
  <input type="text" id="result" /><br /><br />
  <label>Harga bata</label><br />

  <img src="{%static 'images/rp.png'%}" alt="" id="icon3" />
  <input type="text" id="harga" />
</center>

<script>
  function openForm() {
    document.getElementById("cdetail").style.display = "block";
  }
  function closeForm() {
    document.getElementById("cdetail").style.display = "none";
  }

  function calc() {
    var n1 = parseFloat(document.getElementById("n1").value);
    var n2 = parseFloat(document.getElementById("n2").value);
    var n3 = parseFloat(document.getElementById("n3").value);
    var n4 = parseFloat(document.getElementById("n4").value);

    var result = (document.getElementById("result").value =
      (n1 * n2 * n4 || n1 * n2 * 11).toFixed(0));
    document.getElementById("harga").value = result * n3 || result * 2500;
  }
</script>
{%endblock%}

hitung/templates/batamerah.html
{%extends 'base2.html'%} {% load static %} {%block content%} <br /><br />
<center>
  <div class="navbar">
  <div class="row">
    <div class="column">
      <a href="{% url 'menu:menu' %}"><img src="{%static 'images/back.png'%}" alt="" id="back"></a>
      <br />
    </div>
    <div class="column">
      <h4>Bata Merah</h4>
      <br />
    </div>
    <div class="column">
     <img src="{%static 'images/icon.png'%}" alt="" id="back">
      <br />
    </div>
  </div>
  </div>
  <br />
 
  <label for="n1">Tinggi Dinding</label><br />
  <img src="{%static 'images/m.png'%}" alt="" id="icon2" />
  <input type="text" id="n1" /><br /><br />

  <label for="n2">Panjang Dinding</label><br />
  <img src="{%static 'images/m.png'%}" alt="" id="icon2" />
  <input type="text" id="n2" /><br />

  <p id="lebihlengkap"onclick="openForm();">Lebih Detail <b>&#8645;</b></p>
  
  <div id="cdetail" >
    <p id="lebihlengkap"onclick="closeForm();">Lebih Detail <b>&#8645;</b></p>
    <label for="n3">Harga per pcs (default = Rp. 700)</label><br />
    <img src="{%static 'images/rp.png'%}" alt="" id="icon3" />
    <input type="text" id="n3" /><br /><br />

    <label for="n3">Bata per m2 (default = 65)</label><br />
    <img src="{%static 'images/buah.png'%}" alt="" id="icon3" />
    <input type="text" id="n4" /><br /><br />

  </div>

  <button onclick="calc();" id="hitung">HITUNG</button><br />
  <br /><br />
  <label>Jumlah buah bata</label><br />
  <img src="{%static 'images/buah.png'%}" alt="" id="icon4" />
  <input type="text" id="result" /><br /><br />
  <label>Harga bata</label><br/>

  <img src="{%static 'images/rp.png'%}" alt="" id="icon3" />
  <input type="text" id="harga" />
</center>

<script>
  function openForm() {
  document.getElementById("cdetail").style.display = "block";
}
function closeForm() {
  document.getElementById("cdetail").style.display = "none";
}

  function calc() {
    var n1 = parseFloat(document.getElementById("n1").value);
    var n2 = parseFloat(document.getElementById("n2").value);
    var n3 = parseFloat(document.getElementById("n3").value);
    var n4 = parseFloat(document.getElementById("n4").value);

    var result = (document.getElementById("result").value = (n1*n2*n4 || n1 * n2 * 65).toFixed(0));
    document.getElementById("harga").value = result * n3 || result * 700 ;
  }
</script>
{%endblock%}

hitung/templates/bataringan.html
{%extends 'base2.html'%} {% load static %} {%block content%} <br /><br />
<center>
  <div class="navbar">
  <div class="row">
    <div class="column">
      <a href="{% url 'menu:menu' %}"><img src="{%static 'images/back.png'%}" alt="" id="back"></a>
      <br />
    </div>
    <div class="column">
      <h4>Bata Ringan</h4>
      <br />
    </div>
    <div class="column">
   <img src="{%static 'images/icon.png'%}" alt="" id="back">
      <br />
    </div>
  </div>
  </div>
  <br />

  <label for="n1">Tinggi Dinding</label><br />
  <img src="{%static 'images/m.png'%}" alt="" id="icon2" />
  <input type="text" id="n1" /><br /><br />

  <label for="n2">Panjang Dinding</label><br />
  <img src="{%static 'images/m.png'%}" alt="" id="icon2" />
  <input type="text" id="n2" /><br />

  <p id="lebihlengkap" onclick="openForm();">Lebih Detail <b>&#8645;</b></p>

  <div id="cdetail">
    <p id="lebihlengkap" onclick="closeForm();">Lebih Detail <b>&#8645;</b></p>
    <label for="n3">Harga per pcs (default = Rp. 5000)</label><br />
    <img src="{%static 'images/rp.png'%}" alt="" id="icon3" />
    <input type="text" id="n3" /><br /><br />

    <label for="n3">Bata per m2 (default = 8,3)</label><br />
    <img src="{%static 'images/buah.png'%}" alt="" id="icon3" />
    <input type="text" id="n4" /><br /><br />
  </div>

  <button onclick="calc();" id="hitung">HITUNG</button><br />
  <br /><br />
  <label>Jumlah buah bata</label><br />
  <img src="{%static 'images/buah.png'%}" alt="" id="icon4" />
  <input type="text" id="result" /><br /><br />
  <label>Harga bata</label><br />

  <img src="{%static 'images/rp.png'%}" alt="" id="icon3" />
  <input type="text" id="harga" />
</center>

<script>
  function openForm() {
    document.getElementById("cdetail").style.display = "block";
  }
  function closeForm() {
    document.getElementById("cdetail").style.display = "none";
  }

  function calc() {
    var n1 = parseFloat(document.getElementById("n1").value);
    var n2 = parseFloat(document.getElementById("n2").value);
    var n3 = parseFloat(document.getElementById("n3").value);
    var n4 = parseFloat(document.getElementById("n4").value);

    var result = (document.getElementById("result").value =
      (n1 * n2 * n4 || n1 * n2 * 8.3).toFixed(0));
    document.getElementById("harga").value = result * n3 || result * 5000;
  }
</script>
{%endblock%}

hitung/templates/harga.html
{%extends 'base2.html'%} {% load static %} {%block content%} <br /><br />
<center>
  
   <div class="navbar">
  <div class="row">
    <div class="column">
      <a href="{% url 'menu:menu' %}"><img src="{%static 'images/back.png'%}" alt="" id="back"></a>
      <br />
    </div>
    <div class="column">
      <h4>Daftar Harga bata</h4>
      <br />
    </div>
    <div class="column">
      <img src="{%static 'images/icon.png'%}" alt="" id="back">
      <br />
    </div>
  </div>
  </div>
  <br />
  
  <br />
  <div style="text-align: left;">
    <p>**Harga bata hanya untuk patokan awal, harga <b>berbeda-beda</b> di setiap tempat.</p>
  <h3 >Bata Merah</h3>
  <p >1. Bata merah hias: Rp 1.200 per buah<br>2. Bata merah standar: Rp 725 per buah <br>3. Bata merah oven: Rp 900 per buah<br>&nbsp;&nbsp;&nbsp;&nbsp;Data diambil dari: www.99.co</p>
  <h3 >Bata Ekspos/ Bata Tempel</h3>
  <p >1. Terracota Biasa: Rp 2.000 per buah<br>2. Terracota Super: Rp 2.750 per buah <br>3. Tempet Alur/Bevel/Cadas: Rp. 4.000 per buah<br>&nbsp;&nbsp;&nbsp;&nbsp;Data diambil dari: www.www.99.co</p>
    <h3 >Bata Ringan</h3>
  <p >1. Bata ringan terbaik: Rp 9.000 per buah<br>2. Bata ringan grade A+: Rp 6.500 per buah <br>3. Bata ringan grade A: Rp 5.000 per buah<br>&nbsp;&nbsp;&nbsp;&nbsp;Data diambil dari: www.99.co</p>
  <h3 >Batako</h3>
  <p >1. Batako press: Rp 1.500 per buah<br>2. Batako hitam press: Rp 1.750 per buah <br>&nbsp;&nbsp;&nbsp;&nbsp;Data diambil dari: www.lamudi.co.id</p>
    </div>
</center>
</script>
{%endblock%}

hitung/templates/panduan.html
{%extends 'base2.html'%} {% load static %} {%block content%} <br /><br />
<center>
  <div class="navbar">
  <div class="row">
    <div class="column">
      <a href="{% url 'menu:menu' %}"><img src="{%static 'images/back.png'%}" alt="" id="back"></a>
      <br />
    </div>
    <div class="column">
      <h4>Kebutuhan Bata Per m2</h4>
      <br />
    </div>
    <div class="column">
     <img src="{%static 'images/icon.png'%}" alt="" id="back">
      <br />
    </div>
  </div>
  </div>
  <br />

  <img src="{%static 'images/ukuran.png'%}" alt="" id="gambarutama"><br><br><br>

  <label for="n1">Panjang Bata</label><br />
  <img src="{%static 'images/cm.png'%}" alt="" id="icon2" />
  <input type="text" id="n1" /><br /><br />

  <label for="n2">Lebar Bata</label><br />
  <img src="{%static 'images/cm.png'%}" alt="" id="icon2" />
  <input type="text" id="n2" placeholder="Boleh dikosongkan"/><br /><br />

  <label for="n3">Tinggi Bata</label><br />
  <img src="{%static 'images/cm.png'%}" alt="" id="icon2" />
  <input type="text" id="n3" /><br /><br />

  <label for="n4">Spesi (Jarak)</label><br />
  <img src="{%static 'images/cm.png'%}" alt="" id="icon2" />
  <input type="text" id="n4" placeholder="Boleh dikosongkan"/><br /><br />

  <button onclick="calc();" id="hitung">HITUNG</button><br />
  <br /><br />
  <label>Jumlah buah bata</label><br />
  <img src="{%static 'images/buah.png'%}" alt="" id="icon4" />
  <input type="text" id="result" /><br /><br />
</center>

<script>

  function calc() {
    var n1 = parseFloat(document.getElementById("n1").value);
    var n2 = parseFloat(document.getElementById("n2").value);
    var n3 = parseFloat(document.getElementById("n3").value);
    var n4 = parseFloat(document.getElementById("n4").value);

    var result = (document.getElementById("result").value = (10000/((n1+n4)*(n3+n4))||10000/((n1)*(n3))).toFixed(2));
  }
</script>
{%endblock%}

hitung/templates/panduan2.html
{%extends 'base2.html'%} {% load static %} {%block content%} <br /><br />
<center>
    <div class="navbar">
  <div class="row">
    <div class="column">
      <a href="{% url 'menu:menu' %}"><img src="{%static 'images/back.png'%}" alt="" id="back"></a>
      <br />
    </div>
    <div class="column">
     <h4>Panduan</h4>
      <br />
    </div>
    <div class="column">
     <img src="{%static 'images/icon.png'%}" alt="" id="back">
      <br />
    </div>
  </div>
  </div>
  <br />
    <h3 style="margin-top:-0.5em;">Panduan Menghitung Bata</h3>
    <img src="{%static 'images/panduan1.gif'%}" alt="" id="gif" style="margin-top: -1em;"><br>
    <img src="{%static 'images/panduan2.gif'%}" alt="" id="gif" style="margin-top: -0.3em;"><br>
    <img src="{%static 'images/panduan3.gif'%}" alt="" id="gif" style="margin-top: -2em;"><br>
    
</center>
{%endblock%}

menu/templates/menu.html
{%extends 'base2.html'%} {% load static %} {%block content%}
<center>
<div id="super">

  <div class="title">
    <a href="{% url 'menu:splash' %}"><h5>HITUNG BATA</h5></a>
    <p id="harga2">Harga Dapat Diubah</p>
   
  </div>
  <div class="main">
    
    <a href="{% url 'hitung:batamerah' %}">
      <div class="container">
      <img src="{%static 'images/batam.png'%}" alt="" class="gambarmenu">
      <p id="menu1">Bata Merah</p><br >
      <p id="menu2">Rp. 600</p>
    </div>
  </a>
  <a href="{% url 'hitung:bataringan' %}">
    <div class="container2">
      <img src="{%static 'images/batar.png'%}" alt="" class="gambarmenu">
      <p id="menu1">Bata Ringan</p><p id="menu2">Rp. 5.000</p></div>
      </a>

      <a href="{% url 'hitung:batako' %}">
      <div class="container3"> <img src="{%static 'images/batak.png'%}" alt="" class="gambarmenu">
      <p id="menu1">Batako&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
      <p id="menu2">Rp. 2.500</p></div>
    </a>
    
    <a href="{% url 'hitung:panduan' %}">
    <div class="container4">
      <img src="{%static 'images/ukuran22.png'%}" alt="" class="gambarmenu">
      <p id="menu1">Kebutuhan Bata</p><p id="menu2"></p>
      <p id="menu2">Per m2</p></div>
    </a>
    
    <a href="{% url 'hitung:harga' %}">
      <div class="container">
      <img src="{%static 'images/harga.jpg'%}" alt="" class="gambarmenu">
      <p id="menu1">Daftar&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p><br>
      <p id="menu2">Harga Bata</p>
    </div>
    
  </a>
  <a href="{% url 'hitung:panduan2' %}">
    <div class="container2">
      <img src="{%static 'images/panduan.png'%}" alt="" class="gambarmenu">
      <p id="menu1">Panduan</p><p id="menu2">Penggunaan aplikasi</p></div>
      </a>
  </div>
  <br><br>

</div>
</center>
{%endblock%}

menu/templates/menu2.html
{%extends 'base2.html'%} {% load static %} {%block content%}
<center>
 <a href="{% url 'menu:menu' %}"><img src="{%static 'images/splash.png'%}" alt="" style="margin-top:18em; width:12em;"></a>
</center>


<script>
         setTimeout(function(){
            window.location.href = 'http://127.0.0.1:8000/menu/';
         }, 1500);
      </script>
{%endblock%}

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Titan+One&display=swap" rel="stylesheet">
  </head>
  <body>
    {%block content%} {%endblock%}
  </body>
</html>

templates/base2.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/styles2.css'%}" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Titan+One&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    {%block content%} {%endblock%}
  </body>
</html>